fragment RankHistoryDay on PlayerRankHistory {
  date
  ranking
  rankedPlays
  ap
}

query playerLayout($playerId: BigInt!, $category: BigInt) {
  playerRankHistories(
    condition: { playerId: $playerId, categoryId: $category }
    last: 30
  ) {
    nodes {
      ...RankHistoryDay
    }
  }
}
