fragment ApDataPoint on AccSaberScore {
  categoryDisplayName
  categoryName
  ap
}

query ApGraphPage($playerId: BigInt!) {
  playerDatum(playerId: $playerId) {
    playerId
    playerName
  }
  categories {
    nodes {
      categoryName
      categoryDisplayName
    }
  }

  categoryAccSaberPlayers(condition: { playerId: $playerId }) {
    nodes {
      categoryName
    }
  }

  accSaberScores(condition: { playerId: $playerId }, orderBy: AP_DESC) {
    nodes {
      ...ApDataPoint
    }
  }
}
