query RankedMapPage($mapId: BigInt!) {
  beatMap(leaderboardId: $mapId) {
    nodeId
    difficulty
    complexity
    leaderboardId
    category {
      categoryDisplayName
    }
    song: song {
      songHash
      songName
      songSubName
      songAuthorName
      beatSaverKey
      levelAuthorName
    }
  }
}
