fragment RankHistoryDay on PlayerRankHistory {
  date
  ranking
  rankedPlays
  ap
}

fragment SkillLevel on CategoryAccSaberPlayer {
  skillLevel
  categoryName
  categoryByCategoryName {
    categoryDisplayName
  }
}

fragment CategoryInfo on Category {
  categoryName
  categoryDisplayName
}

query PlayerLayout($playerId: BigInt!, $category: BigInt!, $historyDays: Int!) {
  playerRankHistories(
    condition: { playerId: $playerId, categoryId: $category }
    last: $historyDays
  ) {
    nodes {
      ...RankHistoryDay
    }
  }
  peak: playerRankHistories(
    condition: { playerId: $playerId, categoryId: $category }
    first: 1
    orderBy: RANKING_ASC
  ) {
    nodes {
      ranking
    }
  }
  categoryAccSaberPlayers(condition: { playerId: $playerId }) {
    nodes {
      categoryName
      ...SkillLevel
    }
  }
  categories {
    nodes {
      ...CategoryInfo
    }
  }
  campaign(id: 0) {
    playerCampaignInfo(playerId: $playerId) {
      milestoneId
      pathCleared
    }
  }
}
