fragment ScoreRow on AccSaberScore {
  scoreId
  ranking
  leaderboardId
  songHash
  songName
  songAuthorName
  difficulty
  categoryDisplayName
  accuracy
  ap
  weightedAp
  timeSet
  complexity
}

query PlayerScoresPage(
  $playerId: BigInt!
  $pageSize: Int!
  $offset: Int!
  $orderBy: [AccSaberScoresOrderBy!]
  $category: String
) {
  accSaberScores(
    condition: { playerId: $playerId, categoryName: $category }
    first: $pageSize
    offset: $offset
    orderBy: $orderBy
  ) {
    nodes {
      ...ScoreRow
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
