fragment RankHistoryDay on PlayerRankHistory {
  date
  ranking
  rankedPlays
  ap
}

fragment SkillLevel on CategoryAccSaberPlayer {
  skillLevel
  categoryName
  categoryByCategoryName {
    categoryDisplayName
  }
}
fragment CategoryInfo on Category {
  categoryName
  categoryDisplayName
}

query PlayerLayout($playerId: BigInt!, $category: BigInt!) {
  playerRankHistories(
    condition: { playerId: $playerId, categoryId: $category }
    last: 30
  ) {
    nodes {
      ...RankHistoryDay
    }
  }

  categoryAccSaberPlayers(condition: { playerId: $playerId }) {
    nodes {
      categoryName
      ...SkillLevel
    }
  }

  categories {
    nodes {
      ...CategoryInfo
    }
  }
  campaign(id: 0) {
    playerCampaignInfo(playerId: $playerId) {
      milestoneId
      pathCleared
    }
  }
}
