name: Deploy to Fly.io
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --local-only"

      - name: Purge Bunny.net cache
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.bunny.net/pullzone/${{ env.BUNNY_ZONE }}/purgeCache"
          method: "POST"
          customHeaders: '{"AccessKey": "${{ secrets.BUNNY_KEY }}"}'
